# Generated by Django 5.2.9 on 2026-02-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_delete_pojects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.TextField(),
        ),
    ]
