# Generated by Django 5.2.9 on 2026-02-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video',
            field=models.URLField(),
        ),
    ]
