# Generated by Django 5.2.9 on 2026-02-06 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='video',
            new_name='video_url',
        ),
    ]
