# Generated by Django 5.2.9 on 2026-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_video_project_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='video_url',
            field=models.URLField(max_length=500),
        ),
    ]
