# Generated by Django 5.2.9 on 2026-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_url',
        ),
        migrations.AddField(
            model_name='project',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
