# Generated by Django 5.2.11 on 2026-02-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_video_url_project_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video_file_land',
            field=models.FileField(blank=True, null=True, upload_to='land_videos/'),
        ),
    ]
