# Generated by Django 5.2.9 on 2026-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_video_file_land'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('short', 'Short Form'), ('long', 'Long Form'), ('ads', 'Ads & VSL')], default='short', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
