# Generated by Django 5.2.9 on 2026-02-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_remove_project_thumbnail_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='video_file_land',
        ),
    ]
